//! Bit-exact ports of the approximate transcendentals upstream CatBoost uses to
//! store and update EXP-domain approxes for `IsStoreExpApprox` losses
//! (`approx_updater_helpers.h:60-72` — Logloss, CrossEntropy, Poisson,
//! LogLinQuantile, PairLogit(-Pairwise), YetiRank(-Pairwise)).
//!
//! Upstream deliberately does NOT use exact `exp`/`log` on the training-fold
//! approx pipeline:
//!
//! - per-LEAF delta exp-ification runs `fmath::expd_v`
//!   (`ExpApproxIf(TArrayRef<double>)` → `NCB::FastExpWithInfInplace` →
//!   `FastExpInplaceAvx2` → `contrib/libs/fmath/fmath.hpp expd_v`);
//! - per-DOC learning-rate application runs
//!   `fast_exp(FastLogf(delta) * lr)` (`ApplyLearningRate<true>`,
//!   `approx_updater_helpers.h:31-33`) — the table-based scalar `fast_exp` from
//!   `library/cpp/fast_exp/fast_exp.cpp` and the Mineiro `FastLogf` from
//!   `library/cpp/fast_log/fast_log.h`.
//!
//! Their approximation error (~1e-6 absolute in log space per application) is
//! NOT noise: it feeds the next iteration's derivatives, accumulates, and by
//! ~10-20 iterations moves greedy split scores across tie-break boundaries. An
//! engine computing exact `exp` diverges from upstream's chosen tree STRUCTURE
//! at iteration scale even when every formula matches (the
//! `ctr_borders_multiprior` 20-iteration localization, 2026-08-02, verified
//! against an instrumented v1.2.10 CLI build: identical fold leaf `(SumDer,
//! SumWeights, delta)` at iteration 0, diverging stored approx — the
//! `ApplyLearningRate` pipeline was the only remaining difference).
//!
//! Every function here is a straight transcription of the upstream source with
//! the same IEEE-754 f64/f32 operation order; the committed reference vectors
//! (`tests/fixtures/fast_approx_ref.txt`, generated by
//! `tests/fixtures/fast_approx_ref_generator.cpp.txt` compiled against the
//! REAL upstream objects) pin bit-for-bit equality.

use std::sync::OnceLock;

// Tests live in a dedicated sibling file (source/test separation, CLAUDE.md —
// no test body in this production file), mounted as a child module so
// `cargo test -p cb-train fast_approx` selects them.
#[cfg(test)]
#[path = "fast_approx_test.rs"]
mod tests;

/// The 65536-entry `exp` table of `library/cpp/fast_exp/fast_exp.cpp`:
/// `ExpTable[i] = std::exp(bits(i << 48))` — one entry per possible top-16-bit
/// pattern of an f64 (sign + exponent + 4 mantissa bits).
fn fast_exp_table() -> &'static [f64; 65536] {
    static TABLE: OnceLock<Box<[f64; 65536]>> = OnceLock::new();
    TABLE.get_or_init(|| {
        let mut t = vec![0.0f64; 65536].into_boxed_slice();
        for (i, slot) in t.iter_mut().enumerate() {
            *slot = f64::from_bits((i as u64) << 48).exp();
        }
        // Infallible: the vec above is exactly 65536 long.
        match <Box<[f64; 65536]>>::try_from(t) {
            Ok(arr) => arr,
            Err(_) => unreachable!(),
        }
    })
}

/// `fast_exp(double)` — `library/cpp/fast_exp/fast_exp.cpp:33-49` verbatim:
/// four rounds of "look up exp of the top-16-bit truncation, subtract the
/// truncated argument", then a final `* (1 + arg)` first-order term.
#[must_use]
pub fn fast_exp(x: f64) -> f64 {
    let table = fast_exp_table();
    let mut arg = x;
    let mut res = 1.0f64;
    for _ in 0..4 {
        let bits = arg.to_bits();
        // `bits >> 48` is provably `< 65536` (a u64 keeps 16 bits after the
        // shift), so the NAN fallback is unreachable — kept only to satisfy the
        // workspace `indexing_slicing` deny without a panic path.
        let chk = table.get((bits >> 48) as usize).copied().unwrap_or(f64::NAN);
        let truncated = f64::from_bits(bits & 0xffff_0000_0000_0000);
        res *= chk;
        arg -= truncated;
    }
    res * (1.0 + arg)
}

/// fmath `ExpdVar` constants (`contrib/libs/fmath/fmath.hpp:151-185`,
/// `sbit = EXPD_TABLE_SIZE = 11`).
const EXPD_SBIT: u32 = 11;
const EXPD_S: usize = 1 << EXPD_SBIT; // 2048
const EXPD_ADJ: u64 = (1u64 << (EXPD_SBIT + 10)) - (1u64 << EXPD_SBIT);
const EXPD_C1: f64 = 1.0;
const EXPD_C2: f64 = 0.166_666_666_852_278_35;
const EXPD_C3: f64 = 3.000_000_002_795_539_4;
/// The "magic shifter" `double(3ULL << 51)`.
const EXPD_B: f64 = 6_755_399_441_055_744.0;

struct ExpdVar {
    /// `tbl[i] = mantissa bits of pow(2.0, i / 2048.0)`.
    tbl: [u64; EXPD_S],
    /// `a = s / ln(2)`.
    a: f64,
    /// `ra = 1 / a`.
    ra: f64,
}

fn expd_var() -> &'static ExpdVar {
    static VAR: OnceLock<ExpdVar> = OnceLock::new();
    VAR.get_or_init(|| {
        let a = EXPD_S as f64 / std::f64::consts::LN_2;
        let mut tbl = [0u64; EXPD_S];
        for (i, slot) in tbl.iter_mut().enumerate() {
            // ::pow(2.0, i * (1.0 / s)) — glibc pow and Rust exp2 agree on the
            // correctly-rounded result for these arguments; the committed
            // reference vectors would catch any host where they did not.
            let v = (i as f64 * (1.0 / EXPD_S as f64)).exp2();
            *slot = v.to_bits() & ((1u64 << 52) - 1);
        }
        ExpdVar { tbl, a, ra: 1.0 / a }
    })
}

/// `fmath::expd_v` per-element semantics (`fmath.hpp:565-608`, the AVX2 loop
/// upstream's `FastExpInplaceAvx2` runs) — clamp, magic-number split into
/// `2^(k/2048)` table lookup + exponent bits, cubic polynomial残 remainder.
///
/// This is the function every per-LEAF delta array passes through
/// (`ExpApproxIf`). The vector loop's tail elements (`n & 3`) go through the
/// scalar `fmath::expd`, whose only in-range difference is the clamp constant —
/// irrelevant below ±708 — so ONE transcription serves both.
#[must_use]
pub fn fmath_expd(x: f64) -> f64 {
    let c = expd_var();
    // Upstream's exact clamp: `_mm256_min_pd` then `_mm256_max_pd` in that
    // order, with the vector loop's OWN constants (they differ from the scalar
    // `expd`'s in the 9th digit). Not `clamp()` — the explicit min-then-max
    // preserves the SSE/AVX NaN-propagation semantics verbatim.
    #[allow(clippy::manual_clamp, clippy::excessive_precision, clippy::unreadable_literal)]
    let x = x.min(709.78272569338397).max(-708.39641853226408);
    let d = x * c.a + EXPD_B;
    let di = d.to_bits();
    // The mask keeps 11 bits, so the index is provably `< 2048`; the NAN
    // fallback is unreachable (workspace `indexing_slicing` deny, no panic path).
    let iax = c
        .tbl
        .get((di & ((1u64 << EXPD_SBIT) - 1)) as usize)
        .copied()
        .unwrap_or(u64::MAX);
    let t = (d - EXPD_B) * c.ra - x;
    let u = ((di.wrapping_add(EXPD_ADJ)) >> EXPD_SBIT) << 52;
    let y = (EXPD_C3 - t) * (t * t) * EXPD_C2 - t + EXPD_C1;
    let did = f64::from_bits(u | iax);
    y * did
}

/// `FastLog2f` — `library/cpp/fast_log/fast_log.h:63-76` (Mineiro fastapprox),
/// all-f32 operation order preserved.
#[must_use]
pub fn fast_log2f(value: f32) -> f32 {
    #[allow(clippy::excessive_precision, clippy::unreadable_literal)]
    {
        let vx_i = value.to_bits();
        let mx_f = f32::from_bits((vx_i & 0x007F_FFFF) | 0x3f00_0000);
        let mut y = vx_i as f32;
        y *= 1.1920928955078125e-7_f32;
        y - 124.22551499_f32 - 1.498030302_f32 * mx_f - 1.72587999_f32 / (0.3520887068_f32 + mx_f)
    }
}

/// `FastLogf` — `0.69314718f * FastLog2f(value)`.
///
/// `approx_constant` is intentionally allowed: `0.69314718` is upstream's OWN
/// truncated `ln(2)` literal (`fast_log.h:85`), NOT the standard-library
/// constant — substituting `f32::consts::LN_2` would change the exact f32 bit
/// pattern and break both Bayesian-bootstrap parity and the exp-domain approx
/// pipeline at the oracle bound.
#[allow(clippy::approx_constant)]
#[must_use]
pub fn fast_logf(value: f32) -> f32 {
    #[allow(clippy::excessive_precision, clippy::unreadable_literal)]
    {
        0.69314718_f32 * fast_log2f(value)
    }
}

/// `ApplyLearningRate<StoreExpApprox = true>`
/// (`approx_updater_helpers.h:31-33`): the per-document learning-rate
/// application on an EXP-domain delta —
/// `fast_exp(FastLogf(approxDelta) * learningRate)`. The `FastLogf` argument
/// conversion `double → float` (round-to-nearest) is part of the upstream
/// semantics and is preserved here.
#[must_use]
pub fn apply_learning_rate_exp(approx_delta_exp: f64, learning_rate: f64) -> f64 {
    #[allow(clippy::cast_possible_truncation)]
    let logf = fast_logf(approx_delta_exp as f32);
    fast_exp(f64::from(logf) * learning_rate)
}

/// The Logloss/CrossEntropy first/second derivative from an EXP-domain approx
/// (`CalcCrossEntropyDerRangeImpl`, `error_functions.cpp:304-334`):
/// `p = 1 - 1/(1+e)`, `Der1 = target - p`, `Der2 = -p * (1 - p)` — the exact
/// upstream rounding order (`1 - 1/(1+e)`, NOT `e/(1+e)`).
#[must_use]
pub fn logloss_ders_exp(exp_approx: f64, target: f64) -> (f64, f64) {
    let p = 1.0 - 1.0 / (1.0 + exp_approx);
    (target - p, -p * (1.0 - p))
}
