//! MSLE eval-metric oracle (LOSS-03 / Plan 06.1-02, D-6.1-06): MSLE is a
//! metric-ONLY loss upstream (`enum_helpers.cpp:200,533-549`) — it is NOT a
//! trainable objective and has NO training oracle (Pitfall 1: `loss_function=MSLE`
//! throws). This test gates the MSLE EVAL-METRIC formula against the committed
//! upstream catboost 1.2.10 `msle_metric/metric_values.npy` per-iteration history
//! at <= 1e-5.
//!
//! The `msle_metric` fixture was generated by training a regression model with a
//! VALID objective (RMSE) but `eval_metric="MSLE"`; its `staged.npy` carries the
//! per-iteration RAW staged approx the metric is computed over, and
//! `metric_values.npy` carries upstream's per-iteration MSLE eval value over the
//! `(x, y_pos)` eval set. The target is the positive-shifted `numeric_tiny.y`
//! (`y_pos = y - min(y) + 1.0`, `target_shift` in config.json) so `log(1+x)` stays
//! in domain.
//!
//! MSLE = `mean_w( (log(1+approx) - log(1+target))^2 )`, approx RAW (isExpApprox
//! asserted false; `metric.cpp:1899-1926`, `GetFinalError = Stats[0]/(Stats[1]+
//! 1e-38)`). We reproduce it via [`cb_train::EvalMetric::Msle`] over EACH
//! iteration's staged-approx slice and compare to `metric_values.npy`.
//!
//! RED until Task 4 lands `EvalMetric::Msle` — the variant does not exist yet, so
//! this file will not compile. That RED state is the Task-1 acceptance signal.
#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic, clippy::indexing_slicing)]

use std::path::PathBuf;

use cb_oracle::{compare_stage, load_f64_vec, Stage};
use cb_train::EvalMetric;
use serde_json::Value;

fn fixture(rel: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("cb-oracle")
        .join("fixtures")
        .join(rel)
}

/// The positive target column `y_pos = y - min(y) + 1.0`, reproducing the exact
/// additive `target_shift` the fixture recorded.
fn load_positive_y() -> Vec<f64> {
    let y = load_f64_vec(&fixture("inputs/numeric_tiny/y.npy")).unwrap();
    let cfg: Value = serde_json::from_str(
        &std::fs::read_to_string(fixture("msle_metric/config.json")).unwrap(),
    )
    .unwrap();
    let shift = cfg["target_shift"].as_f64().unwrap();
    y.into_iter().map(|v| v + shift).collect()
}

#[test]
fn msle_metric_per_iteration_matches_upstream() {
    let target = load_positive_y();
    let n_rows = target.len();

    // Per-iteration RAW staged approx (flat: iter0 [n_rows], iter1 [n_rows], ...).
    let staged = load_f64_vec(&fixture("msle_metric/staged.npy")).unwrap();
    assert_eq!(staged.len() % n_rows, 0, "staged length must be a multiple of n_rows");
    let n_iters = staged.len() / n_rows;

    // Upstream per-iteration MSLE eval history.
    let expected = load_f64_vec(&fixture("msle_metric/metric_values.npy")).unwrap();
    assert_eq!(expected.len(), n_iters, "one MSLE value per iteration");

    // Compute MSLE over each iteration's approx slice (unweighted eval set).
    let actual: Vec<f64> = (0..n_iters)
        .map(|it| {
            let approx = &staged[it * n_rows..(it + 1) * n_rows];
            EvalMetric::Msle
                .eval(approx, &target, &[])
                .unwrap_or_else(|e| panic!("MSLE eval failed at iter {it}: {e:?}"))
        })
        .collect();

    compare_stage(Stage::StagedApprox, &expected, &actual)
        .unwrap_or_else(|e| panic!("MSLE metric diverged from upstream: {e:?}"));
}
