//! ORD-01 permutation oracle — the D-03 linchpin lock.
//!
//! # What this locks
//!
//! The per-fold object permutation generated by [`cb_train::fisher_yates_permutation`]
//! (modern Fisher-Yates over the bit-exact `cb_core::TFastRng64`, block size 1
//! for `N < 1000`) must reproduce upstream catboost 1.2.10's permutation
//! INDEX-FOR-INDEX — NOT at the `1e-5` value tolerance, but integer-exact via
//! `cb_oracle::compare_permutation` (`Stage::Permutation`).
//!
//! # Why integer-exact, and why FIRST (D-03)
//!
//! Both our impl and upstream are seeded by the SAME bitstream-verified RNG, so
//! the permutation is reproducible to the exact index. The permutation is the
//! foundation every downstream value stage (online CTR, ordered approx) is
//! computed UNDER: a CTR prefix or ordered approximant computed in the wrong
//! object order is meaningless. So a single-index permutation mismatch must be
//! rejected BEFORE any value-stage test in a later wave is allowed to run — the
//! comparator short-circuits at the first divergent index (`!=`, not `1e-5`).
//!
//! # Fixtures
//!
//! The committed 05-01 `plain_ctr/` (ORD-03) and `ordered_boost/` (ORD-02)
//! fixtures each carry `permutation_fold0.npy` (`int32`, `Stage::Permutation`,
//! D-02 schema) generated by the offline self-oracle harness from
//! `random_seed = 0`, `permutation_count = 1`, `fold_len_multiplier = 2.0`,
//! `N = 30` (per their `config.json`). Both pin the SAME `N = 30` / `seed = 0`
//! permutation, so the lock holds across both isolation scenarios.

use std::path::PathBuf;

use cb_oracle::compare_permutation;
use cb_train::fisher_yates_permutation;
use ndarray::Array1;
use ndarray_npy::read_npy;

/// Resolve a path under `cb-oracle/fixtures/` from cb-train's manifest dir
/// (mirrors `slice_first_oracle_test.rs::fixture`).
fn fixture(rel: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("cb-oracle")
        .join("fixtures")
        .join(rel)
}

/// Load an `int32` `.npy` permutation fixture as `Vec<i64>` for the integer-exact
/// comparator. `ndarray-npy` returns an error (not a panic) on a dtype/shape
/// mismatch, which is the desired guard against a malformed fixture.
fn load_i32_permutation(rel: &str) -> Vec<i64> {
    let arr: Array1<i32> =
        read_npy(fixture(rel)).unwrap_or_else(|e| panic!("{rel} must load as int32 npy: {e:?}"));
    arr.iter().map(|&x| i64::from(x)).collect()
}

/// The committed fixtures were generated with `random_seed = 0`,
/// `permutation_count = 1`, `N = 30` (per their `config.json`). Fold 0 is the
/// only permutation they pin.
const FIXTURE_SEED: u64 = 0;
const FIXTURE_N: usize = 30;

/// D-03 linchpin: the generated fold-0 permutation must equal `plain_ctr`'s
/// committed `permutation_fold0.npy` integer-exact.
#[test]
fn plain_ctr_permutation_fold0_integer_exact() {
    let expected = load_i32_permutation("plain_ctr/permutation_fold0.npy");
    assert_eq!(expected.len(), FIXTURE_N, "fixture N must be 30");
    let actual: Vec<i64> = fisher_yates_permutation(FIXTURE_N, FIXTURE_SEED)
        .iter()
        .map(|&x| i64::from(x))
        .collect();
    compare_permutation(&expected, &actual)
        .unwrap_or_else(|e| panic!("plain_ctr permutation diverged from upstream (D-03): {e}"));
}

/// D-03 linchpin: same lock against the `ordered_boost` (ORD-02) fixture, which
/// pins the SAME `N = 30` / `seed = 0` permutation in a no-CTR scenario — so the
/// permutation math is isolated from any categorical/CTR variable.
#[test]
fn ordered_boost_permutation_fold0_integer_exact() {
    let expected = load_i32_permutation("ordered_boost/permutation_fold0.npy");
    assert_eq!(expected.len(), FIXTURE_N, "fixture N must be 30");
    let actual: Vec<i64> = fisher_yates_permutation(FIXTURE_N, FIXTURE_SEED)
        .iter()
        .map(|&x| i64::from(x))
        .collect();
    compare_permutation(&expected, &actual).unwrap_or_else(|e| {
        panic!("ordered_boost permutation diverged from upstream (D-03): {e}")
    });
}

/// Falsifiability guard: the integer-exact comparator MUST reject a single
/// transposed index (it is NOT a `1e-5` float compare). This proves the D-03
/// lock can actually fail — a permutation off by one position is caught.
#[test]
fn single_index_transposition_is_rejected() {
    let mut perturbed: Vec<i64> = fisher_yates_permutation(FIXTURE_N, FIXTURE_SEED)
        .iter()
        .map(|&x| i64::from(x))
        .collect();
    let correct = perturbed.clone();
    perturbed.swap(0, 1);
    assert!(
        compare_permutation(&correct, &perturbed).is_err(),
        "the permutation oracle must reject a single transposed index"
    );
}
