//! `sum_models` oracle parity (SPEC `sum_models`, SM-07): the frozen upstream
//! `m0.cbm`/`m1.cbm` float-only oblivious models, merged via
//! `cb_model::sum_models`, reproduce upstream `catboost.sum_models(...)
//! .predict(X, prediction_type="RawFormulaVal")` at <= 1e-5
//! (`crates/cb-oracle/fixtures/model_sum/`, generated by `gen_fixtures.py`).
//!
//! Integration test (under `tests/`) so it can depend on `cb-oracle`, mirroring
//! `apply_oracle_test.rs`.
#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic, clippy::indexing_slicing)]

use std::path::PathBuf;

use cb_model::{load_cbm, predict_raw, sum_models, Model};
use cb_oracle::{compare_stage, load_f64_vec, Stage};
use ndarray::Array2;
use ndarray_npy::read_npy;

/// Resolve a path under `cb-oracle/fixtures/` from cb-model's manifest dir.
fn fixture(rel: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("cb-oracle")
        .join("fixtures")
        .join(rel)
}

/// Load `model_sum/X.npy` as per-feature `f32` SoA columns (the apply storage
/// type, matching `apply_oracle_test.rs`'s convention).
fn load_feature_columns() -> Vec<Vec<f32>> {
    let x: Array2<f64> = read_npy(fixture("model_sum/X.npy"))
        .unwrap_or_else(|e| panic!("model_sum/X.npy must load: {e:?}"));
    (0..x.ncols())
        .map(|fi| x.column(fi).iter().map(|&v| v as f32).collect())
        .collect()
}

fn load_models() -> (Model, Model) {
    let m0 = load_cbm(&fixture("model_sum/m0.cbm"))
        .unwrap_or_else(|e| panic!("model_sum/m0.cbm must load: {e:?}"));
    let m1 = load_cbm(&fixture("model_sum/m1.cbm"))
        .unwrap_or_else(|e| panic!("model_sum/m1.cbm must load: {e:?}"));
    (m0, m1)
}

/// Per-model sanity (runs first): `predict_raw` on the frozen `m0.cbm`/
/// `m1.cbm` reproduces each model's OWN upstream `RawFormulaVal` prediction.
/// Proves apply itself is correct BEFORE any merge, so if the summed
/// assertions below fail, the defect is provably in `sum_models` arithmetic,
/// not `predict_raw`.
#[test]
fn sum_models_oracle_inputs_apply() {
    let columns = load_feature_columns();
    let (m0, m1) = load_models();

    let actual_m0 = predict_raw(&m0, &columns);
    let expected_m0 = load_f64_vec(&fixture("model_sum/expected_m0.npy")).unwrap();
    compare_stage(Stage::Predictions, &expected_m0, &actual_m0)
        .unwrap_or_else(|e| panic!("m0 predict_raw diverged: {e:?}"));

    let actual_m1 = predict_raw(&m1, &columns);
    let expected_m1 = load_f64_vec(&fixture("model_sum/expected_m1.npy")).unwrap();
    compare_stage(Stage::Predictions, &expected_m1, &actual_m1)
        .unwrap_or_else(|e| panic!("m1 predict_raw diverged: {e:?}"));
}

#[test]
fn sum_models_oracle_w_1_1() {
    let columns = load_feature_columns();
    let (m0, m1) = load_models();
    let merged = sum_models(&[&m0, &m1], &[1.0, 1.0]).expect("compatible sum must succeed");

    let actual = predict_raw(&merged, &columns);
    let expected = load_f64_vec(&fixture("model_sum/expected_w_1_1.npy")).unwrap();
    compare_stage(Stage::Predictions, &expected, &actual)
        .unwrap_or_else(|e| panic!("sum_models(w=[1,1]) diverged: {e:?}"));
}

#[test]
fn sum_models_oracle_w_03_07() {
    let columns = load_feature_columns();
    let (m0, m1) = load_models();
    let merged = sum_models(&[&m0, &m1], &[0.3, 0.7]).expect("compatible sum must succeed");

    let actual = predict_raw(&merged, &columns);
    let expected = load_f64_vec(&fixture("model_sum/expected_w_03_07.npy")).unwrap();
    compare_stage(Stage::Predictions, &expected, &actual)
        .unwrap_or_else(|e| panic!("sum_models(w=[0.3,0.7]) diverged: {e:?}"));
}
