#!/usr/bin/env python3
"""OFFLINE text & embedding per-stage fixture generator (Phase 6.5, FEAT-01/02).

RUN-ONCE / COMMIT discipline (D-09): a BUILD-TIME tool run OUTSIDE CI on a machine
with catboost==1.2.10 importable. It writes committed frozen `.npy` + `model.json`
+ `config.json` fixtures; CI only READS them. NEVER invoked from CI. Re-run by
hand to (re)generate a fixture, then COMMIT.

This is Wave 0 for Phase 6.5: it produces the per-stage SINGLE-THREAD ground truth
(thread_count=1, NOT the -T 4 canondata — RESEARCH A6) that the later tokenizer /
calcer slices (Plans 02-07) oracle against, plus it freezes the D-01 tokenizer /
dictionary instrumented corpus captured from the D-07 instrumented trainer
(Task 1).

CALCERS (one pinned model.json per calcer, thread_count=1, seed pinned):
    Text  (FEAT-01): BoW, NaiveBayes, BM25  -> fixtures/text_calcers/<calcer>/
    Embed (FEAT-02): LDA, KNN               -> fixtures/embedding_calcers/<calcer>/

PER-STAGE FIXTURES per calcer dir (the established 06.3/06.4 pattern, but as .npy
because text/embedding models can ONLY be exported in `cbm` format — upstream
`model_exporter.cpp:152` rejects JSON export when text/embedding features exist, so
the `model.json` path the borders/leaf calcer fixtures use elsewhere is impossible
here; the live single-thread trainer's per-stage arrays are frozen directly):
    splits.npy        per-tree split BORDER value, tree order (Stage::Splits)
    leaf_values.npy   per-tree leaf values, tree order   (Stage::LeafValues)
    leaf_weights.npy  per-tree leaf weights, tree order   (audit / partition)
    staged.npy        per-iteration staged RawFormulaVal  (Stage::StagedApprox)
    predictions.npy   final RawFormulaVal predictions     (Stage::Predictions)
    model.cbm         the binary model (full-fidelity reload; text/embedding-safe)
    config.json       pinned {seed, catboost_version, thread_count} (cb_oracle schema)
    params.json       the FULL pinned param set (audit; superset of config.json)

TOKENIZER/DICTIONARY D-01 CORPUS (fixtures/text_tokenizer/):
    captured from the instrumented trainer's CB_INSTRUMENT_LOG dump (Task 1) over
    the SAME corpus: token_stream / dict_ids / ttext events frozen as JSON +
    config.json. Generated by `--tokenizer-corpus` AFTER building the instrumented
    trainer; it shells out to the staged instrumented `_catboost.so`.

CORPUS (A4 — OLB boundary is strict `< 1000`):
    The learn pool is a SMALL deterministic text+embedding corpus of LEARN_ROWS
    rows. LEARN_ROWS < 1000 -> the data-dependent OccurrenceLowerBound resolves to
    1 (options_helper.cpp:394-401 `poolSize < 1000 ? 1 : 5`). We RECORD the exact
    learn-pool row count and PIN OccurrenceLowerBound = 1 explicitly in every
    config (no assumption — the count is asserted at generation time).

Run (OFFLINE, after ensuring `.venv` has catboost==1.2.10):
    .venv/bin/python gen_text_embedding_fixtures.py --inputs        # write corpus inputs
    .venv/bin/python gen_text_embedding_fixtures.py --calcers       # all 5 calcer fixtures
    .venv/bin/python gen_text_embedding_fixtures.py --tokenizer-corpus \
        --instr-pkg /tmp/cb_build313/instr_pkg                      # D-01 instrumented corpus
    .venv/bin/python gen_text_embedding_fixtures.py --all --instr-pkg /tmp/cb_build313/instr_pkg
"""
from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path

import numpy as np

GENERATOR_DIR = Path(__file__).resolve().parent
FIXTURES = GENERATOR_DIR.parent / "fixtures"
TEXT_TOKENIZER_DIR = FIXTURES / "text_tokenizer"
TEXT_CALCERS_DIR = FIXTURES / "text_calcers"
EMBEDDING_CALCERS_DIR = FIXTURES / "embedding_calcers"
INPUTS_DIR = FIXTURES / "text_embedding_inputs"

CATBOOST_VERSION = "1.2.10"
RANDOM_SEED = 20260618
DEPTH = 2
ITERATIONS = 5
LEARNING_RATE = 0.3
LEAF_ESTIMATION_ITERATIONS = 1
EMBED_DIM = 4

# Data-dependent default (options_helper.cpp:394-401): poolSize < 1000 -> 1 else 5.
# Our learn pool is intentionally small, so this PINS to 1. Asserted at gen time.
OCCURRENCE_LOWER_BOUND_PINNED = 1
MAX_DICTIONARY_SIZE_PINNED = 50000

# ---------------------------------------------------------------------------
# FROZEN CORPUS. A small, deterministic, binary-labelled text+embedding pool. The
# vocabulary is deliberately tiny and repetitive so the dictionary, the per-class
# token frequencies (NaiveBayes/BM25), and the per-class embedding clouds (LDA/KNN)
# are all well-conditioned and reproducible. ByDelimiter (space) tokenization +
# lowercasing are upstream defaults (D-02).
# ---------------------------------------------------------------------------
_POS_TEXTS = [
    "good great movie",
    "good film great",
    "great good film",
    "great great good",
    "good good great",
    "good movie great film",
    "great wonderful good",
    "good great great",
]
_NEG_TEXTS = [
    "bad awful film",
    "awful movie bad",
    "bad bad awful",
    "awful awful bad",
    "bad film awful",
    "awful bad movie film",
    "bad terrible awful",
    "awful bad bad",
]


def _build_corpus() -> tuple[list[str], list[list[float]], list[int]]:
    """Deterministic interleaved text + embedding + binary-label corpus."""
    rng = np.random.default_rng(RANDOM_SEED)
    texts: list[str] = []
    labels: list[int] = []
    embeds: list[list[float]] = []
    # Two well-separated embedding clouds (one per class) so LDA/KNN have signal.
    pos_center = np.array([1.0, 1.0, -1.0, -1.0])
    neg_center = np.array([-1.0, -1.0, 1.0, 1.0])
    for pos_t, neg_t in zip(_POS_TEXTS, _NEG_TEXTS):
        texts.append(pos_t)
        labels.append(1)
        embeds.append((pos_center + 0.25 * rng.normal(size=EMBED_DIM)).tolist())
        texts.append(neg_t)
        labels.append(0)
        embeds.append((neg_center + 0.25 * rng.normal(size=EMBED_DIM)).tolist())
    return texts, embeds, labels


LEARN_ROWS = len(_POS_TEXTS) + len(_NEG_TEXTS)  # == 16, strictly < 1000 -> OLB=1


def _make_pool(texts, embeds, labels):
    import pandas as pd
    from catboost import Pool

    df = pd.DataFrame({"text0": texts})
    df["emb0"] = [list(map(float, row)) for row in embeds]
    return Pool(
        data=df,
        label=labels,
        text_features=["text0"],
        embedding_features=["emb0"],
    )


# ByDelimiter (space) tokenizer + frequency Word dictionary; BoW additionally over
# a BiGram dictionary (Pitfall 4: default classification BoW = [Bigram, Word]).
def _text_processing(calcer: str) -> dict:
    tokenizers = [
        {"tokenizer_id": "Space", "separator_type": "ByDelimiter", "delimiter": " ", "lowercasing": "true"}
    ]
    dictionaries = [
        {
            "dictionary_id": "Word",
            "gram_order": "1",
            "occurrence_lower_bound": str(OCCURRENCE_LOWER_BOUND_PINNED),
            "max_dictionary_size": str(MAX_DICTIONARY_SIZE_PINNED),
        },
        {
            "dictionary_id": "Bigram",
            "gram_order": "2",
            "occurrence_lower_bound": str(OCCURRENCE_LOWER_BOUND_PINNED),
            "max_dictionary_size": str(MAX_DICTIONARY_SIZE_PINNED),
        },
    ]
    dicts = {"BoW": ["Bigram", "Word"], "NaiveBayes": ["Word"], "BM25": ["Word"]}
    feature_processing = [
        {
            "feature_calcers": [calcer],
            "dictionaries_names": dicts[calcer],
            "tokenizers_names": ["Space"],
        }
    ]
    return {
        "feature_processing": {"default": feature_processing},
        "dictionaries": dictionaries,
        "tokenizers": tokenizers,
    }


# Embedding calcer specs (test.py:10468 EMBEDDING_CALCER_OPTIONS — fixture axes).
EMBEDDING_CALCER_SPECS = {
    "LDA": "LDA:reg=0.05:likelihood=true",
    "KNN": "KNN:k=3",
}

TEXT_CALCERS = ["BoW", "NaiveBayes", "BM25"]
EMBEDDING_CALCERS = ["LDA", "KNN"]


def _base_params() -> dict:
    return {
        "loss_function": "Logloss",
        "iterations": ITERATIONS,
        "depth": DEPTH,
        "learning_rate": LEARNING_RATE,
        "leaf_estimation_iterations": LEAF_ESTIMATION_ITERATIONS,
        "boosting_type": "Plain",
        "bootstrap_type": "No",
        "random_strength": 0,
        "random_seed": RANDOM_SEED,
        "thread_count": 1,
        "allow_writing_files": False,
    }


def _cb_oracle_config() -> dict:
    """The minimal schema cb_oracle::FixtureConfig deserializes (seed/version/threads)."""
    return {
        "seed": RANDOM_SEED,
        "catboost_version": CATBOOST_VERSION,
        "thread_count": 1,
    }


def write_inputs() -> None:
    INPUTS_DIR.mkdir(parents=True, exist_ok=True)
    texts, embeds, labels = _build_corpus()
    assert len(texts) == LEARN_ROWS, (len(texts), LEARN_ROWS)
    assert LEARN_ROWS < 1000, "learn pool must be < 1000 rows so OLB resolves to 1 (A4)"
    (INPUTS_DIR / "texts.json").write_text(json.dumps(texts, indent=2), encoding="utf-8")
    np.save(INPUTS_DIR / "embeddings.npy", np.asarray(embeds, dtype=np.float64), allow_pickle=False)
    np.save(INPUTS_DIR / "labels.npy", np.asarray(labels, dtype=np.float64), allow_pickle=False)
    meta = {
        "catboost_version": CATBOOST_VERSION,
        "learn_rows": LEARN_ROWS,
        "embed_dim": EMBED_DIM,
        "random_seed": RANDOM_SEED,
        "occurrence_lower_bound_pinned": OCCURRENCE_LOWER_BOUND_PINNED,
        "occurrence_lower_bound_rule": "options_helper.cpp:394-401 poolSize<1000 ? 1 : 5; learn_rows=%d < 1000 -> 1" % LEARN_ROWS,
        "max_dictionary_size_pinned": MAX_DICTIONARY_SIZE_PINNED,
        "tokenizer": "ByDelimiter(space) + lowercasing (D-02 defaults)",
        "dictionaries": {"BoW": ["Bigram", "Word"], "NaiveBayes": ["Word"], "BM25": ["Word"]},
        "embedding_calcer_specs": EMBEDDING_CALCER_SPECS,
        "pinned_params": _base_params(),
    }
    (INPUTS_DIR / "meta.json").write_text(json.dumps(meta, indent=2), encoding="utf-8")
    print(f"wrote corpus inputs under {INPUTS_DIR} (learn_rows={LEARN_ROWS}, OLB={OCCURRENCE_LOWER_BOUND_PINNED})")


_BORDER_RE = re.compile(r"bin=([-0-9.eE+]+)")


def _tree_split_borders(model, pool) -> list[float]:
    """Per-tree split BORDER values in tree order, parsed from `_get_tree_splits`.

    Text/embedding models cannot be dumped to JSON, so the split borders are read
    from the textual split descriptions (`... bin=<border>`) the python API exposes.
    Every split string must carry a `bin=` border or we refuse (no fabrication).
    """
    borders: list[float] = []
    for t in range(model.tree_count_):
        for s in model._get_tree_splits(t, pool):
            m = _BORDER_RE.search(s)
            if m is None:
                raise SystemExit(f"split string without a bin= border (tree {t}): {s!r}")
            borders.append(float(m.group(1)))
    return borders


def _freeze_model(scenario_dir: Path, model, pool, params: dict) -> None:
    scenario_dir.mkdir(parents=True, exist_ok=True)
    # Binary model (full fidelity; the only export format text/embedding models allow).
    model.save_model(str(scenario_dir / "model.cbm"), format="cbm")
    # Per-stage numeric ground truth (all from the live single-thread trainer).
    borders = np.asarray(_tree_split_borders(model, pool), dtype=np.float64)
    np.save(scenario_dir / "splits.npy", borders, allow_pickle=False)
    leaf_values = np.asarray(model.get_leaf_values(), dtype=np.float64).reshape(-1)
    np.save(scenario_dir / "leaf_values.npy", leaf_values, allow_pickle=False)
    leaf_weights = np.asarray(model.get_leaf_weights(), dtype=np.float64).reshape(-1)
    np.save(scenario_dir / "leaf_weights.npy", leaf_weights, allow_pickle=False)
    staged = [np.asarray(p, dtype=np.float64).reshape(-1) for p in model.staged_predict(pool, prediction_type="RawFormulaVal")]
    staged_flat = np.concatenate(staged) if staged else np.array([], dtype=np.float64)
    np.save(scenario_dir / "staged.npy", staged_flat.astype(np.float64), allow_pickle=False)
    predictions = np.asarray(model.predict(pool, prediction_type="RawFormulaVal"), dtype=np.float64).reshape(-1)
    np.save(scenario_dir / "predictions.npy", predictions, allow_pickle=False)
    (scenario_dir / "config.json").write_text(json.dumps(_cb_oracle_config(), indent=2), encoding="utf-8")
    (scenario_dir / "params.json").write_text(json.dumps(params, indent=2), encoding="utf-8")
    print(
        f"  froze {scenario_dir.relative_to(FIXTURES.parent)} "
        f"(splits={len(borders)}, leaves={len(leaf_values)}, preds={len(predictions)})"
    )


def gen_text_calcer(calcer: str) -> None:
    from catboost import CatBoost

    texts, embeds, labels = _build_corpus()
    pool = _make_pool(texts, embeds, labels)
    params = _base_params()
    params["text_processing"] = _text_processing(calcer)
    model = CatBoost(params)
    model.fit(pool)
    _freeze_model(TEXT_CALCERS_DIR / calcer, model, pool, params)


def gen_embedding_calcer(calcer: str) -> None:
    from catboost import CatBoost

    texts, embeds, labels = _build_corpus()
    pool = _make_pool(texts, embeds, labels)
    params = _base_params()
    params["embedding_calcers"] = [EMBEDDING_CALCER_SPECS[calcer]]
    model = CatBoost(params)
    model.fit(pool)
    _freeze_model(EMBEDDING_CALCERS_DIR / calcer, model, pool, params)


def gen_all_calcers() -> None:
    if not (INPUTS_DIR / "meta.json").exists():
        write_inputs()
    print("text calcers (FEAT-01):")
    for c in TEXT_CALCERS:
        gen_text_calcer(c)
    print("embedding calcers (FEAT-02):")
    for c in EMBEDDING_CALCERS:
        gen_embedding_calcer(c)


# ---------------------------------------------------------------------------
# D-01 tokenizer / dictionary instrumented corpus (Task 1 + D-07).
#
# The token stream, dictionary token->id table, and per-document TText (tokenId,
# count) list are NOT cleanly Python-reachable (D-07). We capture them from the
# instrumented catboost 1.2.10 trainer (built by build_instrumented_trainer.sh):
# train a BoW model over the SAME corpus with CB_INSTRUMENT_LOG set, then parse the
# token_stream / dict_ids / ttext / online_order events out of the JSONL dump and
# freeze them under fixtures/text_tokenizer/.
# ---------------------------------------------------------------------------
_INSTR_FIT_SNIPPET = r'''
import json, sys
import numpy as np
import pandas as pd
from catboost import Pool, CatBoost

texts = json.loads(sys.argv[1])
embeds = json.load(open(sys.argv[2]))
labels = json.load(open(sys.argv[3]))
df = pd.DataFrame({"text0": texts})
df["emb0"] = [list(map(float, r)) for r in embeds]
pool = Pool(data=df, label=labels, text_features=["text0"], embedding_features=["emb0"])
params = json.load(open(sys.argv[4]))
model = CatBoost(params)
model.fit(pool)
print("INSTR_FIT_OK trees", model.tree_count_)
'''


def gen_tokenizer_corpus(instr_pkg: str) -> None:
    """Capture + freeze the D-01 instrumented token/dict/ttext corpus (D-07)."""
    instr_pkg_path = Path(instr_pkg)
    so = instr_pkg_path / "catboost" / "_catboost.so"
    if not so.exists():
        raise SystemExit(
            f"instrumented trainer not found at {so}; run build_instrumented_trainer.sh first"
        )
    if not (INPUTS_DIR / "meta.json").exists():
        write_inputs()
    texts, embeds, labels = _build_corpus()

    TEXT_TOKENIZER_DIR.mkdir(parents=True, exist_ok=True)
    venv_py = str((GENERATOR_DIR.parent.parent.parent / ".venv" / "bin" / "python"))

    with tempfile.TemporaryDirectory() as tmp:
        tmpd = Path(tmp)
        (tmpd / "embeds.json").write_text(json.dumps(embeds), encoding="utf-8")
        (tmpd / "labels.json").write_text(json.dumps(labels), encoding="utf-8")
        fit_script = tmpd / "fit.py"
        fit_script.write_text(_INSTR_FIT_SNIPPET, encoding="utf-8")

        # Two fits so the frozen corpus covers ALL hook categories:
        #   BoW over [Bigram, Word] exercises BOTH the unigram and bigram dictionaries
        #     (token_stream / dict_ids / ttext) AND, via the default embedding calcers,
        #     lda_projection / knn_neighbors.
        #   NaiveBayes is an ONLINE text estimator (D-03), so it additionally fires
        #     online_order + calcer_encoding (the BoW non-online path does not).
        events: dict[str, list] = {}
        per_calcer: dict[str, dict[str, int]] = {}
        for calcer in ("BoW", "NaiveBayes"):
            params = _base_params()
            params["text_processing"] = _text_processing(calcer)
            (tmpd / "params.json").write_text(json.dumps(params), encoding="utf-8")
            log_path = tmpd / f"instr_{calcer}.jsonl"
            env = dict(os.environ)
            env["CB_INSTRUMENT_LOG"] = str(log_path)
            env["PYTHONPATH"] = str(instr_pkg_path)
            proc = subprocess.run(
                [venv_py, str(fit_script), json.dumps(texts),
                 str(tmpd / "embeds.json"), str(tmpd / "labels.json"), str(tmpd / "params.json")],
                env=env, capture_output=True, text=True,
            )
            if proc.returncode != 0:
                raise SystemExit(f"instrumented {calcer} fit failed (rc={proc.returncode}):\n{proc.stderr[-2000:]}")
            print(f"  instrumented {calcer} fit:", proc.stdout.strip())
            calcer_counts: dict[str, int] = {}
            with open(log_path, encoding="utf-8") as fh:
                for line in fh:
                    line = line.strip()
                    if not line:
                        continue
                    try:
                        obj = json.loads(line)
                    except json.JSONDecodeError:
                        continue
                    ev = obj.get("event")
                    if ev is None:
                        continue
                    obj["_calcer"] = calcer
                    events.setdefault(ev, []).append(obj)
                    calcer_counts[ev] = calcer_counts.get(ev, 0) + 1
            per_calcer[calcer] = calcer_counts

    # Freeze ALL 7 instrumented categories: the D-01 tokenizer/dictionary ground
    # truth (token_stream / dict_ids / ttext) plus the online_order / calcer_encoding
    # / lda_projection / knn_neighbors the later calcer oracles (Plans 02-07) consume.
    ALL_CATS = (
        "token_stream", "dict_ids", "ttext",
        "online_order", "calcer_encoding",
        "lda_projection", "knn_neighbors",
    )
    captured = {}
    for cat in ALL_CATS:
        captured[cat] = events.get(cat, [])
        (TEXT_TOKENIZER_DIR / f"{cat}.json").write_text(
            json.dumps(events.get(cat, []), indent=2), encoding="utf-8"
        )
    summary = {
        "catboost_version": CATBOOST_VERSION,
        "learn_rows": LEARN_ROWS,
        "occurrence_lower_bound_pinned": OCCURRENCE_LOWER_BOUND_PINNED,
        "fit_calcers": list(per_calcer.keys()),
        "per_calcer_event_counts": per_calcer,
        "hook_event_counts": {k: len(v) for k, v in events.items()},
        "captured_categories": {k: len(v) for k, v in captured.items()},
        "source": "instrumented catboost 1.2.10 trainer (D-07), CB_INSTRUMENT_LOG; 2 fits (BoW + NaiveBayes)",
    }
    (TEXT_TOKENIZER_DIR / "summary.json").write_text(json.dumps(summary, indent=2), encoding="utf-8")
    (TEXT_TOKENIZER_DIR / "config.json").write_text(json.dumps(_cb_oracle_config(), indent=2), encoding="utf-8")
    print(f"  froze D-01 tokenizer corpus under {TEXT_TOKENIZER_DIR}: {summary['captured_categories']}")
    # Escalate-don't-weaken: every one of the 7 instrumented categories MUST be
    # non-empty across the two fits or the corpus is incomplete — never fabricate.
    missing = [c for c in ALL_CATS if not captured[c]]
    if missing:
        raise SystemExit(
            f"D-01 corpus INCOMPLETE — empty hook categories: {missing}. "
            f"Hook coverage: {summary['hook_event_counts']}. "
            "The instrumented trainer did not emit these; do NOT fabricate — fix the hook."
        )


_LDA_FIT_SNIPPET = r'''
import json, sys
import numpy as np
import pandas as pd
from catboost import Pool, CatBoost

embeds = json.load(open(sys.argv[1]))
labels = json.load(open(sys.argv[2]))
params = json.load(open(sys.argv[3]))
texts = json.load(open(sys.argv[4]))
df = pd.DataFrame({"text0": texts})
df["emb0"] = [list(map(float, r)) for r in embeds]
pool = Pool(data=df, label=labels, text_features=["text0"], embedding_features=["emb0"])
model = CatBoost(params)
model.fit(pool)
print("LDA_INSTR_FIT_OK trees", model.tree_count_)
'''


def gen_lda_scatter_gt(instr_pkg: str) -> None:
    """Capture + freeze the LDA generalized-eigenproblem ground truth (06.5-05).

    Extends the Plan-01 ``lda_projection`` hook with the EXACT scatter inputs
    (``lda_scatter``: regularized betweenMatrix B + totalScatter A, captured BEFORE
    ``ssygst_`` mutates them) so the hand-rolled f32 eigensolver can be re-measured
    against the upstream eigensolve in isolation from the scatter construction.

    The frozen GT lives at ``fixtures/embedding_calcers/LDA/scatter_projection_gt.json``.
    Single-thread (thread_count=1) — see _base_params().
    """
    instr_pkg_path = Path(instr_pkg)
    so = instr_pkg_path / "catboost" / "_catboost.so"
    if not so.exists():
        raise SystemExit(
            f"instrumented trainer not found at {so}; run build_instrumented_trainer.sh "
            "first (it now patches the lda_scatter + lda_project hooks too)."
        )
    if not (INPUTS_DIR / "meta.json").exists():
        write_inputs()
    texts, embeds, labels = _build_corpus()
    venv_py = str((GENERATOR_DIR.parent.parent.parent / ".venv" / "bin" / "python"))

    with tempfile.TemporaryDirectory() as tmp:
        tmpd = Path(tmp)
        (tmpd / "embeds.json").write_text(json.dumps(embeds), encoding="utf-8")
        (tmpd / "labels.json").write_text(json.dumps(labels), encoding="utf-8")
        (tmpd / "texts.json").write_text(json.dumps(texts), encoding="utf-8")
        params = _base_params()
        params["embedding_calcers"] = [EMBEDDING_CALCER_SPECS["LDA"]]
        (tmpd / "params.json").write_text(json.dumps(params), encoding="utf-8")
        fit_script = tmpd / "lda_fit.py"
        fit_script.write_text(_LDA_FIT_SNIPPET, encoding="utf-8")
        log_path = tmpd / "lda_instr.jsonl"
        env = dict(os.environ)
        env["CB_INSTRUMENT_LOG"] = str(log_path)
        env["PYTHONPATH"] = str(instr_pkg_path)
        proc = subprocess.run(
            [venv_py, str(fit_script), str(tmpd / "embeds.json"),
             str(tmpd / "labels.json"), str(tmpd / "params.json"), str(tmpd / "texts.json")],
            env=env, capture_output=True, text=True,
        )
        if proc.returncode != 0:
            raise SystemExit(f"instrumented LDA fit failed (rc={proc.returncode}):\n{proc.stderr[-2000:]}")
        print("  instrumented LDA fit:", proc.stdout.strip())
        scat: list[dict] = []
        proj: list[dict] = []
        with open(log_path, encoding="utf-8") as fh:
            for line in fh:
                line = line.strip()
                if not line:
                    continue
                try:
                    obj = json.loads(line)
                except json.JSONDecodeError:
                    continue
                if obj.get("event") == "lda_scatter":
                    scat.append(obj)
                elif obj.get("event") == "lda_projection":
                    proj.append(obj)

    # Escalate-don't-weaken: the scatter + projection dumps MUST be present.
    if not scat or not proj:
        raise SystemExit(
            "LDA scatter GT INCOMPLETE — lda_scatter / lda_projection events missing. "
            f"(scatter={len(scat)}, projection={len(proj)}). The instrumented trainer did "
            "not emit them; rebuild via build_instrumented_trainer.sh (it applies the "
            "lda_scatter + lda_project hooks). Do NOT fabricate."
        )
    final_s, final_p = scat[-1], proj[-1]
    gt = {
        "source": "instrumented catboost 1.2.10 trainer (D-07/D-09), CB_INSTRUMENT_LOG; "
                  "LDA reg=0.05 likelihood=true; thread_count=1",
        "corpus": "text_embedding_inputs (16 rows, EMBED_DIM=4, binary)",
        "dim": final_s["dim"],
        "reg_param": 0.05,
        "final_flush_scatter_inner": final_s["scatter_inner"],
        "final_flush_scatter_total": final_s["scatter_total"],
        "final_projection_matrix": final_p["matrix"],
        "final_eigenvalues": final_p["eigenvalues"],
        "n_flushes": len(scat),
        "note": (
            "scatter_inner = regularized betweenMatrix (B), scatter_total = totalScatter (A), "
            "captured BEFORE ssygst_ mutates them in place. projection = trailing-rows copy of "
            "the ssyev_ output (the reduced-problem dominant eigenvector, NOT back-transformed). "
            "RE-MEASUREMENT (06.5-05): the hand-rolled f32 scatter matches B/A to <=5e-10/0, and "
            "the hand-rolled eigensolve matches BOTH f64 scipy AND f32 reference LAPACK ssygv "
            "(dominant eigenvalue 38.45, eigvec [0.597,0.563,-0.439,-0.365]); but the upstream "
            "vendored-CLAPACK ssyev_ dump reports a dominant eigenvalue (376.67) inconsistent with "
            "its own eigenvector (Rayleigh quotient 38.28) and an eigenvector 4.9e-2 away from "
            "reference. See 06.5-05-SUMMARY divergence report."
        ),
    }
    out = EMBEDDING_CALCERS_DIR / "LDA" / "scatter_projection_gt.json"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(gt, indent=2), encoding="utf-8")
    print(f"  froze LDA scatter+projection GT under {out} ({len(scat)} flushes)")


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--inputs", action="store_true", help="write corpus inputs only")
    parser.add_argument("--calcers", action="store_true", help="generate all 5 calcer fixtures")
    parser.add_argument("--tokenizer-corpus", action="store_true", help="freeze the D-01 instrumented corpus")
    parser.add_argument("--lda-scatter-gt", action="store_true",
                        help="freeze the LDA generalized-eigenproblem GT (scatter + projection, 06.5-05)")
    parser.add_argument("--instr-pkg", type=str, default=os.environ.get("INSTR_STAGE_PKG", "/tmp/cb_build313/instr_pkg"),
                        help="path to the staged instrumented catboost package (contains catboost/_catboost.so)")
    parser.add_argument("--all", action="store_true", help="inputs + calcers + tokenizer-corpus + lda-scatter-gt")
    args = parser.parse_args(argv)

    FIXTURES.mkdir(parents=True, exist_ok=True)

    if args.all:
        write_inputs()
        gen_all_calcers()
        gen_tokenizer_corpus(args.instr_pkg)
        gen_lda_scatter_gt(args.instr_pkg)
        return 0
    if args.inputs:
        write_inputs()
    if args.calcers:
        gen_all_calcers()
    if args.tokenizer_corpus:
        gen_tokenizer_corpus(args.instr_pkg)
    if args.lda_scatter_gt:
        gen_lda_scatter_gt(args.instr_pkg)
    if not (args.inputs or args.calcers or args.tokenizer_corpus or args.lda_scatter_gt):
        write_inputs()
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
